#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../.."
export PATH="/Users/soquendo/.nvm/versions/node/v22.23.2/bin:$PATH"
export COREPACK_ENABLE_NETWORK=0
node --input-type=module - "$@" <<'JS'
// Real browser/API/PostgreSQL verification. All mutations use an isolated DB/API.
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import crypto from 'node:crypto'
import http from 'node:http'
import {execFileSync,spawn} from 'node:child_process'
import {pathToFileURL} from 'node:url'
const args=process.argv.slice(2),root=process.cwd(),failure=args.includes('--exercise-cleanup-failure')
const storageOnly=args.includes('--storage-boundary-only')
const apiImage=args.includes('--api-image')?args[args.indexOf('--api-image')+1]:null
const evidence=path.resolve(args.includes('--evidence-dir')?args[args.indexOf('--evidence-dir')+1]:fs.mkdtempSync(path.join(os.tmpdir(),'venue-m6-ui-evidence-')))
assert(!evidence.startsWith(root+path.sep),'Evidence must be outside Git');fs.mkdirSync(evidence,{recursive:true})
const owned=fs.mkdtempSync(path.join(os.tmpdir(),'venue-m6-ui-owned-')),token=crypto.randomBytes(6).toString('hex'),identifier='venueops_m6_ui_'+token
const project='venue-network-operations-console',apiName=project+'-m6-ui-'+token,migrationName=apiName+'-migration',dbContainer=project+'-incident-db-1',password=crypto.randomBytes(32).toString('hex')
const checks=[],browserRequests=[],proxyRequests=[]
let role=false,database=false,api=false,migration=false,mutated=false,chrome=null,vite=null,promProxy=null,promEnabled=true,cdp=null,base='',origin='',cleaning=false
const log=(label,detail={})=>{const entry={time:new Date().toISOString(),label,...detail};checks.push(entry);console.log(JSON.stringify(entry))}
const save=(name,value)=>{const text=JSON.stringify(value,null,2);assert(!text.includes(password));fs.writeFileSync(path.join(evidence,name),text+'\n')}
function run(command,...argv){try{return execFileSync(command,argv,{encoding:'utf8',timeout:60000,maxBuffer:16*1024*1024,stdio:['pipe','pipe','pipe']}).trim()}catch(e){throw new Error(`${command} failed: ${String(e.stderr?.toString()||e.message).replaceAll(password,'<redacted>')}`)}}
function sql(query,db=identifier){try{return execFileSync('docker',['exec','-i',dbContainer,'psql','-X','-v','ON_ERROR_STOP=1','-U','venueops','-d',db,'-At'],{input:query,encoding:'utf8',timeout:15000,stdio:['pipe','pipe','pipe']}).trim()}catch(e){throw new Error('Scoped PostgreSQL assertion failed: '+String(e.stderr??'').replaceAll(password,'<redacted>'))}}
async function request(url,method='GET',body){const started=Date.now(),r=await fetch(url,{method,body:body===undefined?undefined:JSON.stringify(body),headers:body===undefined?{}:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000)});const raw=await r.text();let value;try{value=JSON.parse(raw)}catch{value=raw};return {status:r.status,value,contentType:r.headers.get('content-type'),elapsed:Date.now()-started}}
async function expect(url,status=200,method='GET',body){const r=await request(url,method,body);assert.equal(r.status,status,`${url}: ${JSON.stringify(r.value)}`);if(status===503)assert(r.elapsed<12000);return r.value}
const delay=ms=>new Promise(r=>setTimeout(r,ms))
async function poll(label,fn,seconds=35){const end=Date.now()+seconds*1000;while(Date.now()<end){if(await fn())return;await delay(250)}throw new Error('Timed out: '+label)}
const counts=()=>sql('SELECT (SELECT count(*) FROM "Incidents"),(SELECT count(*) FROM "IncidentAccessPoints"),(SELECT count(*) FROM "IncidentEvents");')
const envFingerprint=()=>({hash:crypto.createHash('sha256').update(fs.readFileSync('.env')).digest('hex'),mode:fs.statSync('.env').mode&0o777})
function infrastructure(){const ids=run('docker','ps','-aq','--filter','label=com.docker.compose.project='+project).split(/\s+/);const all=JSON.parse(run('docker','inspect',...ids));assert.equal(all.length,5);return Object.fromEntries(all.map(c=>{assert(c.State.Running&&!c.State.Paused);if(c.State.Health)assert.equal(c.State.Health.Status,'healthy');return[c.Config.Labels['com.docker.compose.service'],{id:c.Id,image:c.Image,bindings:c.HostConfig.PortBindings,mounts:c.Mounts.sort((a,b)=>a.Destination.localeCompare(b.Destination)),command:c.Config.Cmd}]}))}
async function healthy(){const o=await expect('http://127.0.0.1:8080/api/operations/overview');return o.probe.success&&o.simulatorScrape.up&&o.accessPoints.every((a,i)=>a.operational&&!a.degraded&&a.alertState==='inactive'&&a.degradationAlertState==='inactive'&&a.clients===[42,35,28,31][i]&&a.channelUtilizationRatio===[.55,.48,.41,.46][i]&&a.managementLatencySeconds===[.018,.016,.015,.017][i]&&a.managementPacketLossRatio===[.002,.001,.001,.002][i])}
async function reset(){await expect('http://127.0.0.1:8081/simulation/event-day/reset',200,'POST')}
async function peak(){mutated=true;await expect('http://127.0.0.1:8081/simulation/event-day/position',200,'PUT',{elapsedMinutes:360});await poll('collected Zone A degradation',async()=>{const o=await expect(base+'/api/operations/overview');return o.accessPoints.slice(0,2).every(a=>a.degraded)})}
async function stop(child){if(!child||child.exitCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),delay(5000)]);if(child.exitCode===null){child.kill('SIGKILL');await new Promise(r=>child.once('exit',r))}}
async function cleanup(){if(cleaning)return;cleaning=true;const errors=[];async function step(fn){try{await fn()}catch(e){errors.push(e.message)}}
 await step(async()=>{if(mutated){await reset();await poll('cleanup collected baseline',healthy,35)}})
 await step(async()=>{cdp?.close();await stop(chrome)})
 await step(async()=>{if(vite)await vite.close();if(promProxy){promProxy.closeAllConnections();await new Promise(r=>promProxy.close(r))}})
 await step(()=>{if(api){try{const logs=run('docker','logs',apiName);fs.writeFileSync(path.join(evidence,'isolated-api.log'),logs.replaceAll(password,'<redacted>'))}finally{run('docker','rm','--force',apiName);api=false}}})
 await step(()=>{if(migration)run('docker','rm','--force',migrationName)})
 await step(()=>{if(database){sql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${identifier}' AND pid<>pg_backend_pid();`,'postgres');sql(`DROP DATABASE ${identifier};`,'postgres');database=false}})
 await step(()=>{if(role){sql(`DROP ROLE ${identifier};`,'postgres');role=false}})
 await step(()=>fs.rmSync(owned,{recursive:true,force:true}))
 save('cleanup.json',{errors,removed:{api:!api,database:!database,role:!role,privateDirectory:!fs.existsSync(owned)}})
 if(errors.length)throw new Error('Cleanup failed: '+errors.join('; '))
}
process.once('SIGINT',()=>{void cleanup().finally(()=>process.exit(130))});process.once('SIGTERM',()=>{void cleanup().finally(()=>process.exit(143))})
class Cdp {
 constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();this.listeners=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);if(p){clearTimeout(p.timer);this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)}}else for(const fn of this.listeners.get(m.method)??[])Promise.resolve(fn(m.params)).catch(e=>{this.eventError=e})})}
 async send(method,params={},session=true){if(this.eventError)throw this.eventError;const id=++this.id;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error('CDP timeout: '+method))},20000);this.pending.set(id,{resolve,reject,timer});this.ws.send(JSON.stringify({id,method,params,...(session&&this.session?{sessionId:this.session}:{})}))})}
 on(method,fn){const list=this.listeners.get(method)??[];list.push(fn);this.listeners.set(method,list);return()=>this.listeners.set(method,list.filter(f=>f!==fn))}
 close(){for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error('Browser verification closed'))}this.pending.clear();this.ws.close()}
}
async function js(expression){const r=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+': '+r.exceptionDetails.exception?.description);return r.result.value}
const text=()=>js('document.body.innerText')
async function contains(value,seconds=30){await poll('browser: '+value,async()=>(await text()).includes(value),seconds)}
async function click(label,scope='document'){await js(`(()=>{const b=[...${scope}.querySelectorAll('button,a')].find(e=>e.textContent.trim()===${JSON.stringify(label)});if(!b||b.disabled)throw Error('Missing/enabled control: '+${JSON.stringify(label)});b.click()})()`)}
async function input(selector,value){await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||e.disabled)throw Error('Missing/enabled input');const p=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(p,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`)}
async function navigate(suffix){await cdp.send('Page.navigate',{url:origin+suffix});await contains('Venue Network Operations Console')}
async function reload(){await cdp.send('Page.reload');await contains('Venue Network Operations Console');await delay(500)}
async function snapshot(name,full=true){const r=await cdp.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:full});fs.writeFileSync(path.join(evidence,name+'.png'),Buffer.from(r.data,'base64'))}
const currentId=()=>js('Number(new URL(location.href).searchParams.get("incident"))')
const detail=id=>expect(base+'/api/incidents/'+id)
async function browserVersion(version){await poll('browser version '+version,async()=>await js(`document.querySelector('[data-incident-version]')?.dataset.incidentVersion===${JSON.stringify(String(version))}`))}
async function waitAction(id){const d=await detail(id);await browserVersion(d.version);await poll('workflow controls ready',()=>js("!document.querySelector('#incident-note')?.disabled"));return d}
async function command(id,path,payload){const d=await detail(id);return expect(base+`/api/incidents/${id}/${path}`,200,path==='responder'?'PUT':'POST',{commandId:crypto.randomUUID(),expectedVersion:d.version,...payload})}
function mutationCount(){return browserRequests.filter(r=>['POST','PUT'].includes(r.method)&&r.url.includes('/api/incidents')).length}
async function loseResponse(action,dispatch){let paused=null;const off=cdp.on('Fetch.requestPaused',async p=>{if(p.request.url.includes(action)&&[200,201].includes(p.responseStatusCode)){paused=p}else await cdp.send('Fetch.continueRequest',{requestId:p.requestId})});await cdp.send('Fetch.enable',{patterns:[{urlPattern:'*/api/incidents'+action,requestStage:'Response'}]});await dispatch();await poll('response paused after server completion',()=>paused!==null);return {p:paused,finish:async()=>{await cdp.send('Fetch.failRequest',{requestId:paused.requestId,errorReason:'Failed'});off();await cdp.send('Fetch.disable')}}}
let failureError=null,beforeInfra,beforeEnv,historyUrl,historyBefore
try {
 assert.equal(process.version,'v22.23.2');beforeInfra=infrastructure();beforeEnv=envFingerprint();assert.equal(beforeEnv.mode,0o600)
 assert.equal(sql('SELECT (SELECT count(*) FROM "Incidents"),(SELECT count(*) FROM "IncidentAccessPoints"),(SELECT count(*) FROM "IncidentEvents");','venueops_incidents'),'0|0|0')
 await expect('http://127.0.0.1:8080/health/ready/incidents');assert(await healthy());assert.equal((await expect('http://127.0.0.1:8081/simulation/event-day')).mode,'baseline')
 const end=Math.floor(Date.now()/1000)-15;historyUrl='http://127.0.0.1:9090/api/v1/query_range?'+new URLSearchParams({query:'venue_ap_operational{ap_id="ap-001"}',start:String(end-120),end:String(end),step:'5'});historyBefore=await expect(historyUrl);assert(historyBefore.data.result[0].values.length>0);save('history-before.json',{url:historyUrl,result:historyBefore});save('infrastructure-before.json',beforeInfra)
 // Own resources before making any simulator mutation; no normal incident data is written.
 role=true;sql(`CREATE ROLE ${identifier} LOGIN PASSWORD '${password}';`,'postgres');database=true;sql(`CREATE DATABASE ${identifier} OWNER ${identifier};`,'postgres')
 promProxy=http.createServer(async(req,res)=>{try{if(!promEnabled){res.writeHead(503);res.end('Scoped monitoring dependency unavailable');return}const r=await fetch('http://127.0.0.1:9090'+req.url,{signal:AbortSignal.timeout(10000)});res.writeHead(r.status,{'Content-Type':r.headers.get('content-type')??'application/json'});res.end(Buffer.from(await r.arrayBuffer()))}catch{res.writeHead(503);res.end('Scoped monitoring proxy unavailable')}});await new Promise(r=>promProxy.listen(0,'127.0.0.1',r))
 const envFile=path.join(owned,'api.env');fs.writeFileSync(envFile,`Incidents__Host=incident-db\nIncidents__Database=${identifier}\nIncidents__Username=${identifier}\nIncidents__Password=${password}\nPrometheus__BaseUrl=http://host.docker.internal:${promProxy.address().port}\n`,{mode:0o600})
 const image=apiImage??beforeInfra['venue-api'].image;migration=true;run('docker','run','--rm','--pull','never','--name',migrationName,'--network',project+'_default','--env-file',envFile,image,'--migrate-incidents');migration=false
 api=true;run('docker','run','--detach','--pull','never','--name',apiName,'--network',project+'_default','--publish','127.0.0.1::8080','--env-file',envFile,image)
 const port=JSON.parse(run('docker','inspect',apiName))[0].NetworkSettings.Ports['8080/tcp'][0];assert.equal(port.HostIp,'127.0.0.1');base='http://127.0.0.1:'+port.HostPort
 await poll('isolated readiness',async()=>{try{return(await request(base+'/health/ready/incidents')).status===200}catch{return false}})
 if(storageOnly){
  // Reproduce the original first-use failure on a terminated pooled connection.
  await peak()
  const created=await expect(base+'/api/incidents',201,'POST',{title:'Storage boundary verification',responderLabel:null,creationCommandId:crypto.randomUUID(),accessPoints:[{apId:'ap-001',expectedCondition:'degraded'}]})
  const note={commandId:crypto.randomUUID(),expectedVersion:1,text:'Stored before dependency outage'}
  const receipt=await expect(base+`/api/incidents/${created.id}/notes`,200,'POST',note)
  const stored=await detail(created.id),beforeCounts=counts()
  await expect(base+'/api/incidents')
  sql(`ALTER ROLE ${identifier} NOLOGIN;`,'postgres')
  const terminated=sql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE usename='${identifier}';`,'postgres');assert(terminated.includes('t'))
  const outcomes=[]
  for(const [url,method,body] of [[base+'/api/incidents','GET'],[base+`/api/incidents/${created.id}`,'GET'],[base+`/api/incidents/${created.id}/notes`,'POST',note],[base+'/api/incidents','POST',{title:'Unavailable storage',responderLabel:null,creationCommandId:crypto.randomUUID(),accessPoints:[{apId:'ap-001',expectedCondition:'degraded'}]}]]){
   const response=await request(url,method,body);assert.equal(response.status,503);assert.equal(response.value.status,503);assert(response.contentType.includes('application/problem+json'));assert.equal(response.value.title,'Incident storage is unavailable');assert(response.elapsed<12000);assert(JSON.stringify(response.value).length<1000);assert(!JSON.stringify(response.value).includes(identifier));outcomes.push({method,path:new URL(url).pathname,...response})
  }
  await expect(base+'/health/live');await expect(base+'/api/operations/overview');assert.equal(counts(),beforeCounts)
  const providerLog=run('docker','logs',apiName);assert(providerLog.includes('57P01'));assert(providerLog.includes('System.InvalidOperationException'));save('storage-outage.json',outcomes)
  sql(`ALTER ROLE ${identifier} LOGIN;`,'postgres');await poll('storage readiness recovers',async()=> (await request(base+'/health/ready/incidents')).status===200)
  assert.deepEqual(await detail(created.id),stored);assert.equal((await expect(base+'/api/incidents')).items[0].id,created.id);assert.deepEqual(await expect(base+`/api/incidents/${created.id}/notes`,200,'POST',note),receipt);assert.equal(counts(),beforeCounts)
  await command(created.id,'notes',{text:'New work after restoration'});assert.equal((await detail(created.id)).version,stored.version+1)
  log('Recognized wrapped 57P01 returned bounded 503 for list/detail/create/workflow; liveness/monitoring stayed 200; stored state and workflow recovered',{id:created.id,outcomes:outcomes.map(r=>({method:r.method,path:r.path,status:r.status,elapsed:r.elapsed}))})
 }else{
 const {createServer}=await import(pathToFileURL(path.join(root,'src/VenueOps.Web/node_modules/vite/dist/node/index.js')))
 vite=await createServer({root:path.join(root,'src/VenueOps.Web'),configFile:path.join(root,'src/VenueOps.Web/vite.config.ts'),server:{host:'127.0.0.1',port:0,strictPort:true,proxy:{'/api':{target:base,changeOrigin:true,configure(proxy){proxy.on('proxyReq',(proxyReq,req)=>{proxyRequests.push({time:Date.now(),url:req.url,target:base,method:req.method})});proxy.on('proxyRes',(res)=>{res.headers['x-venue-ui-verification-api']=apiName})}}}}});await vite.listen();origin='http://127.0.0.1:'+vite.httpServer.address().port
 assert.equal(vite.config.server.proxy['/api'].target,base);const probe=await fetch(origin+'/api/incidents');assert.equal(probe.headers.get('x-venue-ui-verification-api'),apiName);assert.deepEqual(await probe.json(),{items:[],hasMore:false,nextBeforeId:null});assert.equal(counts(),'0|0|0');log('All /api traffic configured for isolated API; empty HTTP response carries proxy evidence',{origin,api:base})
 const profile=path.join(owned,'chrome');fs.mkdirSync(profile);const chromeLog=fs.openSync(path.join(owned,'chrome.log'),'w');chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-address=127.0.0.1','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore',chromeLog,chromeLog]});fs.closeSync(chromeLog)
 await poll('Chrome DevTools',()=>fs.existsSync(path.join(profile,'DevToolsActivePort')));const [debugPort,debugPath]=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').trim().split('\n');const ws=new WebSocket('ws://127.0.0.1:'+debugPort+debugPath);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});cdp=new Cdp(ws)
 const target=await cdp.send('Target.createTarget',{url:'about:blank'},false);cdp.session=(await cdp.send('Target.attachToTarget',{targetId:target.targetId,flatten:true},false)).sessionId;await cdp.send('Page.enable');await cdp.send('Runtime.enable');await cdp.send('Network.enable');await cdp.send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false})
 cdp.on('Network.requestWillBeSent',p=>{if(p.request.url.startsWith(origin+'/api'))browserRequests.push({time:Date.now(),url:p.request.url,method:p.request.method,body:p.request.postData??null})})
 await peak();await navigate('/');await poll('current Zone A create available',()=>js("!!document.querySelector('.zone-card button') && !document.querySelector('.zone-card button').disabled"));await click('Create incident',"document.querySelector('.zone-card')");await contains('Frozen scope: Zone A');assert((await text()).includes('ap-001 · degraded'));assert((await text()).includes('ap-002 · degraded'));await input('#incident-create-title','Closeout browser incident');await click('Create incident',"document.querySelector('[aria-labelledby=\"create-incident-heading\"]')");await contains('Captured at incident creation');const id=await currentId();assert(id>0);const initial=await detail(id);assert.equal(initial.monitoringEvidence.accessPoints.length,2);assert.equal(counts(),'1|2|1');assert(initial.monitoringEvidence.accessPoints.every(a=>a.degraded&&a.operational));await snapshot('created-detail');log('Browser created one Zone A incident from frozen current context',{id})
 if(failure)throw new Error('Intentional cleanup exercise after browser startup, incident commit and simulator mutation')
 await click('Incidents',"document.querySelector('nav')");await contains('Closeout browser incident');await click(initial.number+' · Closeout browser incident');await contains('Captured at incident creation')
 await input('#incident-responder','Network Operations');await click('Save responder');await browserVersion(2);await waitAction(id)
 await click('Start investigating');await click('Save transition');await browserVersion(3);await waitAction(id)
 await input('#incident-note','Inspected Zone A current quality.');await click('Add note');await browserVersion(4);await waitAction(id)
 await reset();await poll('monitoring recovery',healthy);await poll('browser current quality recovered',()=>js("[...document.querySelectorAll('[aria-labelledby=\"current-network-heading\"] .status-badge')].every(e=>e.textContent==='Healthy')"));assert.equal((await detail(id)).status,'Investigating');assert.deepEqual((await detail(id)).monitoringEvidence,initial.monitoringEvidence)
 await click('Monitor');await input('#incident-transition-note','Watching recovered service.');await click('Save transition');await browserVersion(5);await waitAction(id)
 await click('Resolve');await input('#incident-transition-note','Recovered and verified.');await click('Save transition');await browserVersion(6);await reload();await browserVersion(6);assert.equal((await detail(id)).status,'Resolved')
 await click('Reopen');await input('#incident-transition-note','Follow-up investigation.');await click('Save transition');await browserVersion(7);await contains('Recovered and verified.');await contains('Follow-up investigation.');await snapshot('workflow-reopened');log('Browser responder, investigation, note, recovery, monitoring, resolution, reload and reopening passed',{id,version:7})
 // Lost creation response: pause only at response stage, then inspect PostgreSQL before dropping delivery.
 await peak();await click('Monitoring',"document.querySelector('nav')");await poll('current Zone A create available',()=>js("!!document.querySelector('.zone-card button') && !document.querySelector('.zone-card button').disabled"));await click('Create incident',"document.querySelector('.zone-card')");await input('#incident-create-title','Lost response incident')
 const lostCreate=await loseResponse('',()=>click('Create incident',"document.querySelector('[aria-labelledby=\"create-incident-heading\"]')"));const createPayload=JSON.parse(lostCreate.p.request.postData);assert.match(createPayload.creationCommandId,/^[0-9a-f-]{36}$/);const storedId=Number(sql(`SELECT "Id" FROM "Incidents" WHERE "CreationCommandId"='${createPayload.creationCommandId}';`));assert(storedId>0);assert.equal(sql(`SELECT count(*) FROM "IncidentEvents" WHERE "IncidentId"=${storedId};`),'1');await lostCreate.finish();await contains('Previous create attempt may have completed');await reload();const postsBeforeRetry=mutationCount();await delay(1000);assert.equal(mutationCount(),postsBeforeRetry);await click('Review saved create attempt');await contains('Previous create attempt may have completed')
 promEnabled=false;await poll('isolated monitoring failure',async()=> (await request(base+'/api/operations/overview')).status===503);await delay(5500);await click('Retry same request');await contains('Captured at incident creation');assert.equal(await currentId(),storedId);assert.deepEqual(JSON.parse(browserRequests.filter(r=>r.method==='POST'&&new URL(r.url).pathname==='/api/incidents').at(-1).body),createPayload);assert.equal(sql(`SELECT count(*) FROM "Incidents" WHERE "CreationCommandId"='${createPayload.creationCommandId}';`),'1');assert.equal(await js("sessionStorage.getItem('venueops.incidentCreateAttempt.v1')"),null);log('Response-stage create loss recovered by explicit identical replay with monitoring unavailable',{id:storedId})
 await contains('Retained/stale telemetry');await click('Incidents',"document.querySelector('nav')");await contains('Lost response incident');await click('INC-'+String(storedId).padStart(6,'0')+' · Lost response incident');await contains('Captured at incident creation');await input('#incident-note','Stored workflow without Prometheus');await click('Add note');await browserVersion(2)
 await click('Monitoring',"document.querySelector('nav')");await contains('Telemetry refresh failed');assert(await js("[...document.querySelectorAll('.incident-create-action')].every(e=>e.disabled)"));promEnabled=true;await poll('monitoring restored',async()=> (await request(base+'/api/operations/overview')).status===200);await navigate('/?view=incidents&incident='+storedId);await browserVersion(2)
 const lostAction=await loseResponse('/'+storedId+'/notes',async()=>{await input('#incident-note','Lost note response');await click('Add note')});const actionPayload=JSON.parse(lostAction.p.request.postData);assert.equal(sql(`SELECT count(*) FROM "IncidentEvents" WHERE "IncidentId"=${storedId} AND "CommandId"='${actionPayload.commandId}';`),'1');assert.equal((await detail(storedId)).version,3);await lostAction.finish();await contains('Previous incident action may have completed');await reload();await browserVersion(3);const mutationBefore=mutationCount();await delay(750);assert.equal(mutationCount(),mutationBefore);await click('Retry same request');await waitAction(storedId);assert.equal((await detail(storedId)).version,3);assert.equal(sql(`SELECT count(*) FROM "IncidentEvents" WHERE "IncidentId"=${storedId};`),'3');assert.deepEqual(JSON.parse(browserRequests.filter(r=>r.url.endsWith('/notes')).at(-1).body),actionPayload);log('Response-stage workflow loss replayed immutable receipt once',{id:storedId,version:3})
 await input('#incident-note','Draft preserved across concurrent change');await command(storedId,'notes',{text:'Second operator update'});await click('Add note');await contains('Another change occurred');await browserVersion(4);assert.equal(await js("document.querySelector('#incident-note').value"),'Draft preserved across concurrent change');const rejected=JSON.parse(browserRequests.filter(r=>r.url.endsWith('/notes')).at(-1).body),conflictCount=mutationCount();await delay(750);assert.equal(mutationCount(),conflictCount);await click('Reviewed current state');await click('Add note');await browserVersion(5);const reviewed=JSON.parse(browserRequests.filter(r=>r.url.endsWith('/notes')).at(-1).body);assert.notEqual(reviewed.commandId,rejected.commandId);assert.equal(reviewed.expectedVersion,4);log('Version conflict retained draft, fetched latest state and required explicit new command')
 // Provider failure is isolated to this role; production monitoring stays available.
 sql(`ALTER ROLE ${identifier} NOLOGIN;`,'postgres');sql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE usename='${identifier}';`,'postgres');await expect(base+'/health/live');await expect(base+'/api/operations/overview');await expect(base+'/api/incidents',503);await click('Refresh incident');await contains('Incident storage is unavailable');await click('Incidents',"document.querySelector('nav')");await contains('Incident storage is unavailable');await click('Monitoring',"document.querySelector('nav')");await contains('Venue zones');const pollsBefore=browserRequests.filter(r=>r.url.endsWith('/operations/overview')).length;await delay(10500);assert(browserRequests.filter(r=>r.url.endsWith('/operations/overview')).length>=pollsBefore+2);sql(`ALTER ROLE ${identifier} LOGIN;`,'postgres');await poll('database access restored',async()=> (await request(base+'/health/ready/incidents')).status===200);await click('Incidents',"document.querySelector('nav')");await contains('Lost response incident');log('Real DB outage remained scoped; process liveness and monitoring continued; explicit navigation recovered')
 // Seed only isolated chronology through the real workflow API.
 for(let i=0;i<102;i++)await command(storedId,'notes',{text:'Pagination evidence '+i});const latest=await detail(storedId);assert(latest.hasEarlierEvents);await navigate('/?view=incidents&incident='+storedId);await browserVersion(latest.version);assert.equal(await js("document.querySelectorAll('[data-event-sequence]').length"),100)
 await click('Load earlier activity');await contains('Incident created');const sequences=await js("[...document.querySelectorAll('[data-event-sequence]')].map(e=>Number(e.dataset.eventSequence))");assert.equal(sequences.length,latest.version);assert.equal(new Set(sequences).size,sequences.length);assert.deepEqual(sequences,[...sequences].sort((a,b)=>a-b));await browserVersion(latest.version)
 await click('Refresh incident');await poll('latest bounded activity reset',()=>js("document.querySelectorAll('[data-event-sequence]').length===100"));let older=null;const off=cdp.on('Fetch.requestPaused',async p=>{older=p});await cdp.send('Fetch.enable',{patterns:[{urlPattern:'*/api/incidents/*?beforeEventSequence=*',requestStage:'Response'}]});await click('Load earlier activity');await poll('older page held at response boundary',()=>older!==null);await click('Refresh incident');await browserVersion(latest.version);try{await cdp.send('Fetch.continueRequest',{requestId:older.requestId})}catch(e){if(!/Invalid InterceptionId|Invalid interception|not found/.test(e.message))throw e}off();await cdp.send('Fetch.disable');await delay(500);assert.equal(await js("document.querySelectorAll('[data-event-sequence]').length"),100);log('Older chronology prepended in order; obsolete older response could not replace latest generation',{version:latest.version})
 await snapshot('timeline-latest');await cdp.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await js('window.scrollTo(0,0)');await snapshot('mobile-detail',false);assert(await js('document.documentElement.scrollWidth<=window.innerWidth+1'));await cdp.send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false})
 const startPoll=Date.now();await delay(11000);const ticks=proxyRequests.filter(r=>r.url==='/api/operations/overview'&&r.time>=startPoll);assert(ticks.length>=2&&ticks.length<=3);for(let i=1;i<ticks.length;i++)assert(ticks[i].time-ticks[i-1].time>3500);log('Existing overview polling remained bounded without catch-up bursts',{observations:ticks.length})
 save('browser-requests.json',browserRequests);save('proxy-requests.json',proxyRequests);save('representative-detail.json',await detail(storedId));assert(proxyRequests.every(r=>r.target===base));log('Hosted operator UI verification passed')
 }
} catch(e){failureError=e;console.error(e.stack??e);if(cdp){try{save('failure-page.json',{text:await text()});await snapshot('failure')}catch{}}}
finally {try{await cleanup()}catch(e){failureError=e}save('checks.json',checks)}
try {
 assert.deepEqual(infrastructure(),beforeInfra);assert.deepEqual(envFingerprint(),beforeEnv);assert.equal(sql('SELECT (SELECT count(*) FROM "Incidents"),(SELECT count(*) FROM "IncidentAccessPoints"),(SELECT count(*) FROM "IncidentEvents");','venueops_incidents'),'0|0|0');await expect('http://127.0.0.1:8080/health/ready/incidents');let healthySince=null;await poll('final baseline and alerts stable across two evaluation intervals',async()=>{if(!await healthy()){healthySince=null;return false}healthySince??=Date.now();return Date.now()-healthySince>=10000},45);const sim=await expect('http://127.0.0.1:8081/simulation/event-day');assert.equal(sim.mode,'baseline');assert(sim.accessPoints.every(a=>a.scenario==='healthy'))
 const targets=await expect('http://127.0.0.1:9090/api/v1/targets');assert.equal(targets.data.activeTargets.length,5);assert(targets.data.activeTargets.every(t=>t.health==='up'));const after=await expect(historyUrl);assert.deepEqual(after,historyBefore);save('history-after.json',after);save('final-state.json',{simulator:sim,normalCounts:'0|0|0',healthyTargets:5,historyPreserved:true,envPreserved:true,infrastructurePreserved:true});log('Cleanup and final normal runtime/history/credential preservation passed')
}catch(e){failureError=e;console.error(e.stack??e)}
if(failureError){if(failure&&failureError.message.startsWith('Intentional cleanup exercise')){log('Intentional failure cleanup proved');process.exitCode=2}else process.exitCode=1}else process.exitCode=0
JS
