// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VenueOps.Api;

#nullable disable

namespace VenueOps.Api.Migrations
{
    [DbContext(typeof(IncidentDbContext))]
    partial class IncidentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VenueOps.Api.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MonitoringCaptureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OverviewGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponderLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Incidents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Incident_Open", "\"Status\" = 'Open'");
                        });
                });

            modelBuilder.Entity("VenueOps.Api.IncidentAccessPointContext", b =>
                {
                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AlertState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("ChannelUtilizationRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("Clients")
                        .HasColumnType("integer");

                    b.Property<string>("DegradationAlertState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Degraded")
                        .HasColumnType("boolean");

                    b.Property<double?>("ManagementLatencySeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ManagementPacketLossRatio")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Operational")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("IncidentId", "ApId");

                    b.ToTable("IncidentAccessPoints", (string)null);
                });

            modelBuilder.Entity("VenueOps.Api.IncidentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "Kind")
                        .IsUnique()
                        .HasFilter("\"Kind\" = 'Created'");

                    b.ToTable("IncidentEvents", (string)null);
                });

            modelBuilder.Entity("VenueOps.Api.IncidentAccessPointContext", b =>
                {
                    b.HasOne("VenueOps.Api.Incident", null)
                        .WithMany("AccessPoints")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VenueOps.Api.IncidentAlertObservation", "DegradationAlert", b1 =>
                        {
                            b1.Property<long>("IncidentAccessPointContextIncidentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("IncidentAccessPointContextApId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ApId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateTimeOffset>("ObservedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("TelemetrySource")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Zone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("IncidentAccessPointContextIncidentId", "IncidentAccessPointContextApId");

                            b1.ToTable("IncidentAccessPoints");

                            b1.WithOwner()
                                .HasForeignKey("IncidentAccessPointContextIncidentId", "IncidentAccessPointContextApId");
                        });

                    b.OwnsOne("VenueOps.Api.IncidentAlertObservation", "DownAlert", b1 =>
                        {
                            b1.Property<long>("IncidentAccessPointContextIncidentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("IncidentAccessPointContextApId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ApId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateTimeOffset>("ObservedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("TelemetrySource")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Zone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("IncidentAccessPointContextIncidentId", "IncidentAccessPointContextApId");

                            b1.ToTable("IncidentAccessPoints");

                            b1.WithOwner()
                                .HasForeignKey("IncidentAccessPointContextIncidentId", "IncidentAccessPointContextApId");
                        });

                    b.Navigation("DegradationAlert");

                    b.Navigation("DownAlert");
                });

            modelBuilder.Entity("VenueOps.Api.IncidentEvent", b =>
                {
                    b.HasOne("VenueOps.Api.Incident", null)
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VenueOps.Api.Incident", b =>
                {
                    b.Navigation("AccessPoints");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
